version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  assignees:
  - berviantoleo
  groups:
    angular:
      patterns:
        - "@angular/*"
        - "@angular-devkit/*"
    capacitor:
      patterns:
        - "@capacitor/*"
    ionic:
      patterns:
        - "@ionic/*"
        - "@ionic-native/*"
        - "ionic-*"
    karma:
      patterns:
        - "karma*"
        - "jasmine*"
        - "@types/jasmine*"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo
